name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  build_feature:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows External SDK
          - os: macos-latest
            name: Mac External SDK
          #- os: ubuntu-latest
          #  name: Linux External SDK
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build project
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCLAP_SDK_ROOT=deps/clap -DVST3_SDK_ROOT=deps/vst3sdk -DCLAP_WRAPPER_OUTPUT_NAME=testplug
          cmake --build ./build --config Debug
